import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nav: { title: string; href: string; description: string }[] = [
    {
        title: "Home",
        href: "/",
        description: "",
    },
    {
        title: "Posts",
        href: "/posts",
        description: "",
    },
    {
        title: "Photo",
        href: "/photo",
        description: "",
    },
    {
        title: "Blog",
        href: "/blog",
        description: "",
    },
]

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
              <header className="flex justify-between items-center mx-auto px-4 lg:px-0 max-w-[1440px]">
                  <h1 className="text-2xl">Next.js</h1>
                  <nav>
                      <ul className="flex gap-4">
                          {nav.map((item) => (
                              <li key={item.title}>
                                  <Link href={item.href}>{item.title}</Link>
                              </li>
                          ))}
                      </ul>
                  </nav>
              </header>
              {children}
          </body>
      </html>
    );
}